on:
  push:
    branches:
    - master
    - develop/*
  pull_request:
    branches:
    - master
    - develop/*
  workflow_dispatch:

jobs:
  test_runner:
    name: test_runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          cargo test
